insert into AUTHOR(name, surname)
values ('Billie', 'Eilish'),
       ('Doja', 'Cat'),
       ('Taylor', 'Swift'),
       ('Lady', 'Gaga'),
       ('Miley', 'Cyrus'),
       ('Noah', 'Cyrus'),
       ('Travis', 'Scott'),
       ('Megan', 'Thee Stallion'),
       ('Cardi', 'B'),
       ('Niki', 'Minaj'),
       ('Katy', 'Perry'),
       ('Lana', 'Del Rey'),
       ('Melanie', 'Martinez'),
       ('Genevieve', 'Stokes'),
       ('Stella', 'Bennet'),
       ('Ashley', 'Nicolette'),
       ('Imani', 'Rowe'),
       ('Olivia', 'Rodrigo'),
       ('Dominic', 'Fike'),
       ('Finneas', 'OConnell');
